options:
  logsBucket: "gs://my-logs-bucket"
serviceAccount: "634960214697@cloudbuild.gserviceaccount.com"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/mvp-interview-project/my-docker-repo/mvp-interview:v1'
      - '.'

images:
  - 'asia-northeast1-docker.pkg.dev/mvp-interview-project/my-docker-repo/mvp-interview:v1'
